# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: win-64
name: DAG
channels:
- defaults
- conda-forge
dependencies:
  - aiohttp=3.7.3
  - bleach=3.2.1
  - blas=1.0=mkl
  - ipykernel=5.3.4
  - ipython=7.19.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - jedi=0.18.0
  - jupyter=1.0.0
  - markupsafe=1.1.1
  - matplotlib=3.3.2
  - matplotlib-base=3.3.2
  - nbclient=0.5.1
  - nbconvert=6.0.7
  - nbformat=5.0.8
  - notebook=6.1.6
  - numpy=1.19.2
  - numpy-base=1.19.2
  - pandas=1.2.0
  - pandoc=2.11
  - pandocfilters=1.4.3
  - pickleshare=0.7.5
  - pip=20.3.3
  - pyarrow=2.0.0
  - python=3.8.5
  - python-dateutil=2.8.1
  - python_abi=3.8
  - re2=2020.11.01
  - regex=2020.10.15
  - requests=2.25.1
  - scikit-learn=0.23.2
  - scipy=1.5.2
  - seaborn=0.11.1
  - snappy=1.1.8
  - sqlalchemy=1.3.21
  - sqlite=3.33.0
  - terminado=0.9.2
  - thinc=7.4.5
  - tk=8.6.10
  - tornado=6.1
  - tqdm=4.55.1
  - urllib3=1.26.2
  - wasabi=0.8.0
